name: sertifikasi_rangga
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  get_cli: ^1.8.1
  google_fonts: ^6.2.1
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_storage: ^11.7.4
  cached_network_image: ^3.3.1
  image_picker: ^1.1.0
  firebase_auth: ^4.19.4

dev_dependencies: 
  #flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/

